# Generated by Django 6.0 on 2025-12-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Category image for carousel', null=True, upload_to='categories/'),
        ),
    ]
